Repository Datananas/quill-placeholder-autocomplete, pull requests merged in 2018-09, with the labels that each got.

#9 version 1.0.8
  dist/quill-placeholder-autocomplete-module.min.js
  package.json
  src/autocomplete-module.js
Labels: bug

#13 improve query parsing
  dist/quill-placeholder-autocomplete-module.min.js
  dist/quill-placeholder-autocomplete.css
  package-lock.json
  package.json
  src/autocomplete-module.js
  src/autocomplete.css
  src/suggestBlot.js
Labels: bug, enhancement

#15 Fix uppercase suggests
  dist/quill-placeholder-autocomplete-module.min.js
  src/autocomplete-module.js
Labels: bug, enhancement

#16 New end key option
  README.md
  dist/quill-placeholder-autocomplete-module.min.js
  src/autocomplete-module.js
Labels: enhancement

#17 New version 1.2.0
  README.md
  dist/quill-placeholder-autocomplete-module.min.js
  package-lock.json
  package.json
  src/autocomplete-module.js
Labels: enhancement
